routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/verification', 'HomeController@verification')->name('verification');
Route::get('/detail/{slug}', 'DetailController@index')->name('detail');

Route::post('/checkout/create/{id}', 'CheckoutController@create')->name('checkout-create')->middleware(['auth', 'verified']);
Route::get('/checkout/{id}', 'CheckoutController@index')->name('checkout')->middleware(['auth', 'verified']);
Route::get('/checkout/book/{id}', 'CheckoutController@book')->name('checkout-book')->middleware(['auth', 'verified']);
Route::post('/checkout/upload/{id}', 'CheckoutController@upload')->name('checkout-upload')->middleware(['auth', 'verified']);
Route::get('/checkout/confirm/{id}', 'CheckoutController@confirm')->name('checkout-confirm')->middleware(['auth', 'verified']);
Route::delete('/checkout/{id}', 'CheckoutController@delete')->name('checkout-delete')->middleware(['auth', 'verified']);
Route::get('/testimonial/{id}', 'CheckoutController@testimonial')->name('testimonial')->middleware(['auth', 'verified']);
Route::put('/testimonial/{id}', 'CheckoutController@updateTestimonial')->name('testimonial-update')->middleware(['auth', 'verified']);
Route::get('/myorder', 'CheckoutController@order')->name('myorder')->middleware(['auth', 'verified']);

Route::get('/about-us', 'FeatureController@about')->name('about-us');


Route::get('/profile', 'FeatureController@index')->name('profile-index');
Route::put('/profile/{id}', 'FeatureController@profile')->name('profile-update');


Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource('rental-package', 'RentalPackageController');
        Route::resource('transaction', 'TransactionController');
        Route::resource('user', 'UserController');
        Route::get('/transfer', 'TransactionController@transfer')->name('transfer.index');
        Route::delete('/transfer/{transfer}', 'TransactionController@delete')->name('transfer.delete');
    });

Auth::routes(['verify' => true]);

app/RentalPackage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class RentalPackage extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'type', 'slug', 'plat', 'price', 'total', 'status', 'stock', 'name', 'transmission', 'image', 'about'
    ];

    protected $hidden = [];
}

app/Http/Controllers/Admin/RentalPackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\RentalPackageRequest;
use App\RentalPackage;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class RentalPackageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = RentalPackage::paginate(5);
        return view('pages.admin.rental-package.index', [
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.rental-package.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RentalPackageRequest $request)
    {
        $data = $request->all();
        // dd($data);

        $data['slug'] = Str::slug($request->name);
        $data['status'] = ($data['stock'] > 0) ? "Available" : "Unavailable";
        $imgName = $request->file('image')->getClientOriginalName();
        // dd($imgName);
        $data['image'] = $request->file('image')->storeAs(
            'assets/gallery',
            $imgName,
            'public'
        );

        RentalPackage::create($data);

        return redirect()->route('rental-package.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = RentalPackage::findOrFail($id);

        return view('pages.admin.rental-package.edit', compact(('item')));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'type' => 'max:50',
            'plat' => 'max:20',
            'price' => 'integer',
            'total' => 'integer',
            'stock' => 'integer',
            'name' => 'max:50',
            'transmission' => 'max:50',
            'image' => 'mimes:jpeg,png,jpg,gif,svg',
            'about' => 'max:1000'
        ]);

        $data = $request->all();
        // dd($data);

        $data['slug'] = Str::slug($request->name);

        if ($request->hasFile('image')) {
            $imgName = $request->file('image')->getClientOriginalName();
            $data['image'] = $request->file('image')->storeAs(
                'assets/gallery',
                $imgName,
                'public'
            );
        }

        if ($data['stock'] == 0) {
            $data['status'] = 'Unavailable';
        }


        $item = RentalPackage::findOrFail($id);

        $item->update($data);

        return redirect()->route('rental-package.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = RentalPackage::findOrFail($id);
        $item->delete();

        return redirect()->route('rental-package.index');
    }
}

resources/views/pages/admin/rental-package/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Paket Rental Mobil</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <form action="{{route('rental-package.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{old('name')}}">
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <input type="text" class="form-control" name="type" placeholder="Type" value="{{old('type')}}">
                </div>
                <div class="form-group">
                    <label for="transmission">Transmission</label>
                    <input type="text" class="form-control" name="transmission" placeholder="Transmission" value="{{old('transmission')}}">
                </div>
                <div class="form-group">
                    <label for="plat">Plat</label>
                    <input type="text" class="form-control" name="plat" placeholder="Plat Mobil" value="{{old('plat')}}">
                </div>

                <div class="form-group">
                    <label for="total">Total Unit</label>
                    <input type="number" min="0" class="form-control" name="total" placeholder="Total Mobil" value="{{old('total')}}">
                </div>
                <div class="form-group">
                    <label for="stock">Stock Unit</label>
                    <input type="number" min="0" class="form-control" name="stock" placeholder="Stock" value="{{old('stock')}}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" class="form-control" name="image" placeholder="Image">
                </div>
                <div class="form-group">
                    <label for="about">About</label>
                    <textarea name="about" rows="10" class="d-block w-100 form-control">{{old('about')}}</textarea>
                </div>
                <div class="form-group">
                    <label for="price">Price</label>
                    <input type="number" min="0" class="form-control" name="price" placeholder="Price" value="{{old('price')}}">
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Save
                </button>
                <a href="{{route('rental-package.index')}}" class="btn btn-danger btn-block">Cancel</a>
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/rental-package/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Rental Mobil {{$item->name}}</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <form action="{{route('rental-package.update', $item->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{$item->name}}">
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <input type="text" class="form-control" name="type" placeholder="Type" value="{{$item->type}}">
                </div>
                <div class="form-group">
                    <label for="transmission">Transmission</label>
                    <input type="text" class="form-control" name="transmission" placeholder="Transmission" value="{{$item->transmission}}">
                </div>
                <div class="form-group">
                    <label for="plat">Plat</label>
                    <input type="text" class="form-control" name="plat" placeholder="Plat Mobil" value="{{$item->plat}}">
                </div>

                <div class="form-group">
                    <label for="total">Total</label>
                    <input type="number" min="0" class="form-control" name="total" placeholder="Total Mobil" value="{{$item->total}}">
                </div>
                <div class="form-group">
                    <label for="stock">Stock</label>
                    <input type="number" min="0" class="form-control" name="stock" placeholder="Stock" value="{{$item->stock}}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" class="form-control" name="image" placeholder="Image" value="{{$item->image}}">
                </div>
                <div class="form-group">
                    <label for="about">About</label>
                    <textarea name="about" rows="10" class="d-block w-100 form-control">{{$item->about}}</textarea>
                </div>
                <div class="form-group">
                    <label for="price">Price</label>
                    <input type="number" min="0" class="form-control" name="price" placeholder="Price" value="{{$item->price}}">
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Update
                </button>
                <a href="{{route('rental-package.index')}}" class="btn btn-danger btn-block">Cancel</a>
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/rental-package/index.blade.php
@extends('layouts.admin')

@section('active-rental', 'active')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Paket Rental Mobil</h1>
        <a href="{{route('rental-package.create')}}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Paket Rental Mobil
        </a>
    </div>

    <div class="row">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" colspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Transmission</th>
                            <th>Plat</th>
                            <th>Price</th>
                            <th>Total</th>
                            <th>Stock</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $key => $item )
                        <tr>
                            <td>{{$items->firstItem() + $key }}</td>
                            <td>{{ $item->id}}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->transmission }}</td>
                            <td>{{ $item->plat }}</td>
                            <td>{{ $item->price }}</td>
                            <td>{{ $item->total }}</td>
                            <td>{{ $item->stock }}</td>
                            <td>{{ $item->status}}</td>
                            <td>
                                <a href="{{route('rental-package.edit', $item->id)}}" class="btn btn-info">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <form action="{{route('rental-package.destroy', $item->id)}}" method="POST" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="10" class="text-center">No Data</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="float-sm-left mt-1">
                    Showing
                    {{$items->firstItem()}}
                    to
                    {{$items->lastitem()}}
                    of
                    {{$items->total()}}
                    entries
                </div>
                <div class="float-sm-right mt-2">
                    {{$items->links()}}
                </div>
            </div>
        </div>
    </div>

</div>
@endsection