routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/verification', 'HomeController@verification')->name('verification');
Route::get('/detail/{slug}', 'DetailController@index')->name('detail');

Route::post('/checkout/create/{id}', 'CheckoutController@create')->name('checkout-create')->middleware(['auth', 'verified']);
Route::get('/checkout/{id}', 'CheckoutController@index')->name('checkout')->middleware(['auth', 'verified']);
Route::get('/checkout/book/{id}', 'CheckoutController@book')->name('checkout-book')->middleware(['auth', 'verified']);
Route::post('/checkout/upload/{id}', 'CheckoutController@upload')->name('checkout-upload')->middleware(['auth', 'verified']);
Route::get('/checkout/confirm/{id}', 'CheckoutController@confirm')->name('checkout-confirm')->middleware(['auth', 'verified']);
Route::delete('/checkout/{id}', 'CheckoutController@delete')->name('checkout-delete')->middleware(['auth', 'verified']);
Route::get('/testimonial/{id}', 'CheckoutController@testimonial')->name('testimonial')->middleware(['auth', 'verified']);
Route::put('/testimonial/{id}', 'CheckoutController@updateTestimonial')->name('testimonial-update')->middleware(['auth', 'verified']);
Route::get('/myorder', 'CheckoutController@order')->name('myorder')->middleware(['auth', 'verified']);

Route::get('/about-us', 'FeatureController@about')->name('about-us');


Route::get('/profile', 'FeatureController@index')->name('profile-index');
Route::put('/profile/{id}', 'FeatureController@profile')->name('profile-update');


Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource('rental-package', 'RentalPackageController');
        Route::resource('transaction', 'TransactionController');
        Route::resource('user', 'UserController');
        Route::get('/transfer', 'TransactionController@transfer')->name('transfer.index');
        Route::delete('/transfer/{transfer}', 'TransactionController@delete')->name('transfer.delete');
    });

Auth::routes(['verify' => true]);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'ktp', 'address', 'phone', 'sim', 'image', 'roles'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = User::paginate(5);
        return view('pages.admin.user.index', [
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = User::findOrFail($id);

        return view('pages.admin.user.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = User::findOrFail($id);

        return view('pages.admin.user.edit', compact(('item')));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'roles' => 'required|string|in:USER,ADMIN,SUPERADMIN'
        ]);

        $data = $request->all();
        // dd($data);

        $item = User::findOrFail($id);

        $item->update($data);

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit User {{$item->name}} Data</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <form action="{{route('user.update', $item->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="roles">Role</label>
                    <select name="roles" required class="form-control">
                        <option value="{{$item->roles}}">
                            Jangan Ubah ({{$item->roles}})
                        </option>
                        <option value="USER">User</option>
                        <option value="ADMIN">Admin</option>
                        <option value="SUPERADMIN">Super Admin</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Update
                </button>
                <a href="{{route('user.index')}}" class="btn btn-danger btn-block">Cancel</a>
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/user/index.blade.php
@extends('layouts.admin')

@section('active-user', 'active')
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Users</h1>
    </div>

    <div class="row">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" colspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $key => $item )
                        <tr>
                            <td>{{$items->firstItem() + $key }}</td>
                            <td>{{ $item->id}}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->username }}</td>
                            <td>{{ $item->roles }}</td>
                            <td>
                                <a href="{{route('user.show', $item->id)}}" class="btn btn-primary">
                                    <i class="fa fa-eye "></i>
                                </a>
                                <a href="{{route('user.edit', $item->id)}}" class="btn btn-info">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="text-center">No Data</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="float-sm-left mt-1">
                    Showing
                    {{$items->firstItem()}}
                    to
                    {{$items->lastitem()}}
                    of
                    {{$items->total()}}
                    entries
                </div>
                <div class="float-sm-right mt-2">
                    {{$items->links()}}
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/user/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Detail User {{$item->name}}</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>ID</th>
                    <td>{{ $item->id}}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ $item->name}}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ $item->email}}</td>
                </tr>
                <tr>
                    <th>Username</th>
                    <td>{{ $item->username}}</td>
                </tr>
                <tr>
                    <th>Image</th>
                    <td>
                        @if ($item->image == null)
                        <img src="https://ui-avatars.com/api/?name={{$item->name}}" class="rounded-circle" style="width: 50px; height:50px" />
                        @else
                        <img src="/storage/{{$item->image}}" style="width: 50px; height: 50px">
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>KTP</th>
                    <td>{{$item->ktp}}</td>
                </tr>
                <tr>
                    <th>SIM</th>
                    <td>{{$item->sim}}</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>{{$item->address}}</td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>{{$item->phone}}</td>
                </tr>
                <tr>
                    <th>Role</th>
                    <td>{{$item->roles}}</td>
                </tr>
            </table>
        </div>
    </div>

</div>
@endsection