routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/verification', 'HomeController@verification')->name('verification');
Route::get('/detail/{slug}', 'DetailController@index')->name('detail');

Route::post('/checkout/create/{id}', 'CheckoutController@create')->name('checkout-create')->middleware(['auth', 'verified']);
Route::get('/checkout/{id}', 'CheckoutController@index')->name('checkout')->middleware(['auth', 'verified']);
Route::get('/checkout/book/{id}', 'CheckoutController@book')->name('checkout-book')->middleware(['auth', 'verified']);
Route::post('/checkout/upload/{id}', 'CheckoutController@upload')->name('checkout-upload')->middleware(['auth', 'verified']);
Route::get('/checkout/confirm/{id}', 'CheckoutController@confirm')->name('checkout-confirm')->middleware(['auth', 'verified']);
Route::delete('/checkout/{id}', 'CheckoutController@delete')->name('checkout-delete')->middleware(['auth', 'verified']);
Route::get('/testimonial/{id}', 'CheckoutController@testimonial')->name('testimonial')->middleware(['auth', 'verified']);
Route::put('/testimonial/{id}', 'CheckoutController@updateTestimonial')->name('testimonial-update')->middleware(['auth', 'verified']);
Route::get('/myorder', 'CheckoutController@order')->name('myorder')->middleware(['auth', 'verified']);

Route::get('/about-us', 'FeatureController@about')->name('about-us');


Route::get('/profile', 'FeatureController@index')->name('profile-index');
Route::put('/profile/{id}', 'FeatureController@profile')->name('profile-update');


Route::prefix('admin')
    ->namespace('Admin')
    ->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource('rental-package', 'RentalPackageController');
        Route::resource('transaction', 'TransactionController');
        Route::resource('user', 'UserController');
        Route::get('/transfer', 'TransactionController@transfer')->name('transfer.index');
        Route::delete('/transfer/{transfer}', 'TransactionController@delete')->name('transfer.delete');
    });

Auth::routes(['verify' => true]);

app/Http/Controllers/Admin/TransactionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TransactionRequest;
use App\Transaction;
use App\Transfer;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Transaction::with([
            'user', 'rental_package'
        ])->paginate(5);

        return view('pages.admin.transaction.index', [
            'items' => $items
        ]);
    }

    public function transfer()
    {
        $items = Transfer::with([
            'user', 'transaction'
        ])->paginate(5);

        return view('pages.admin.transaction.transfer', [
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TransactionRequest $request)
    {
        $data = $request->all();
        // dd($data);

        $data['slug'] = Str::slug($request->name);

        Transaction::create($data);

        return redirect()->route('transaction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Transaction::with([
            'user', 'rental_package'
        ])->findOrFail($id);

        return view('pages.admin.transaction.detail', compact(('item')));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Transaction::findOrFail($id);

        return view('pages.admin.transaction.edit', compact(('item')));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TransactionRequest $request, $id)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->name);

        $item = Transaction::findOrFail($id);

        $item->update($data);

        return redirect()->route('transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Transaction::findOrFail($id);
        $item->delete();

        return redirect()->back();
    }

    public function delete($id)
    {
        $item = Transfer::findOrFail($id);
        $item->delete();

        return redirect()->back();
    }
}

resources/views/pages/admin/transaction/detail.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Detail Transaksi {{$item->user->name}}</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>ID</th>
                    <td>{{ $item->id}}</td>
                </tr>
                <tr>
                    <th>Mobil</th>
                    <td>{{ $item->rental_package->name}}</td>
                </tr>
                <tr>
                    <th>Penyewa</th>
                    <td>{{ $item->user->name}}</td>
                </tr>
                <tr>
                    <th>Deadline</th>
                    <td>{{ $item->deadline_day}}</td>
                </tr>
                <tr>
                    <th>Waktu Deadline</th>
                    <td>{{ $item->deadline_time}}</td>
                </tr>
                <tr>
                    <th>Total Transaksi</th>
                    <td>Rp {{ $item->transaction_total}}</td>
                </tr>
                <tr>
                    <th>Status Transaksi</th>
                    <td>{{$item->transaction_status}}</td>
                </tr>
                <tr>
                    <th>Start Date</th>
                    <td>{{$item->start_date}}</td>
                </tr>
                <tr>
                    <th>End Date</th>
                    <td>{{$item->end_date}}</td>
                </tr>
                <tr>
                    <th>Pick Up Location</th>
                    <td>{{$item->pick_up_location}}</td>
                </tr>
                <tr>
                    <th>Pick Up Time</th>
                    <td>{{$item->pick_up_time}}</td>
                </tr>
                <tr>
                    <th>Testimonial</th>
                    <td>{{$item->testimonial}}</td>
                </tr>
            </table>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/transaction/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Rental Mobil {{$item->name}}</h1>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>
                {{$error}}
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card shadow">
        <div class="card-body">
            <form action="{{route('transaction.update', $item->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="transaction_status">Status</label>
                    <select name="transaction_status" required class="form-control">
                        <option value="{{ $item->transaction_status }}">
                            Jangan Ubah ({{ $item->transaction_status }})
                        </option>
                        <option value="IN_CART">In Cart</option>
                        <option value="PENDING">Pending</option>
                        <option value="SUCCESS">Success</option>
                        <option value="FAILED">Failed</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Update
                </button>
                <a href="{{route('transaction.index')}}" class="btn btn-danger btn-block">Cancel</a>
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/transaction/index.blade.php
@extends('layouts.admin')

@section('active-transaksi', 'active')
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Transaksi</h1>
    </div>

    <div class="row">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" colspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>Rental</th>
                            <th>User</th>
                            <th>Deadline</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $key => $item )
                        <tr>
                            <td>{{$items->firstitem() + $key }}</td>
                            <td>{{ $item->id}}</td>
                            <td>{{ $item->rental_package->name }}</td>
                            <td>{{ $item->user->name }}</td>
                            <td>{{ $item->deadline_day }}</td>
                            <td>{{ $item->transaction_status }}</td>
                            <td>
                                <a href="{{route('transaction.show', $item->id)}}" class="btn btn-primary">
                                    <i class="fa fa-eye "></i>
                                </a>
                                <a href="{{route('transaction.edit', $item->id)}}" class="btn btn-info">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <form action="{{route('transaction.destroy', $item->id)}}" method="POST" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="7" class="text-center">No Data</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="float-sm-left mt-1">
                    Showing
                    {{$items->firstItem()}}
                    to
                    {{$items->lastitem()}}
                    of
                    {{$items->total()}}
                    entries
                </div>
                <div class="float-sm-right mt-2">
                    {{$items->links()}}
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/pages/admin/transaction/transfer.blade.php
@extends('layouts.admin')

@section('active-transfer', 'active')
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Transaksi</h1>
    </div>

    <div class="row">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" colspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ID</th>
                            <th>ID Transaksi</th>
                            <th>User</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($items as $key => $item )
                        <tr>
                            <td>{{$items->firstItem()+ $key }}</td>
                            <td>{{ $item->id}}</td>
                            <td>{{ $item->transaction->id }}</td>
                            <td>{{ $item->user->name }}</td>
                            <td>
                                <img src="/storage/{{$item->image}}" alt="">
                            </td>
                            <td>
                                <form action="{{route('transfer.delete', $item->id)}}" method="POST" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="text-center">No Data</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="float-sm-left mt-1">
                    Showing
                    {{$items->firstItem()}}
                    to
                    {{$items->lastitem()}}
                    of
                    {{$items->total()}}
                    entries
                </div>
                <div class="float-sm-right mt-2">
                    {{$items->links()}}
                </div>
            </div>
        </div>
    </div>

</div>
@endsection